# Generated by Django 3.2.15 on 2023-01-23 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='siswa',
            name='kelompok_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Siswa.kelompok'),
        ),
    ]
